In [1]:
# Import Statements
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
# Set up the variables
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
# Use OLS model and calculate SSE, check significance
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.973
Model:                            OLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                     557.6
Date:                Mon, 30 Sep 2024   Prob (F-statistic):           1.36e-70
Time:                        15:39:31   Log-Likelihood:                -372.76
No. Observations:                 100   AIC:                             759.5
Df Residuals:                      93   BIC:                             777.8
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -28.8588      7.661     -3.767      0.000     -44.072     -13.645
X1             1.0605      0.124      8.564      0.000       0.815       1.306
X2             1.5916      0.051     30.919      0.000       1.489       1.694
X3             1.1737      0.104     11.340      0.000       0.968       1.379
X4             0.7258      0.128      5.649      0.000       0.471       0.981
X5            -2.1455      0.056    -38.133      0.000      -2.257      -2.034
X6            -0.8759      0.098     -8.909      0.000      -1.071      -0.681
==============================================================================
Omnibus:                        1.523   Durbin-Watson:                   1.885
Prob(Omnibus):                  0.467   Jarque-Bera (JB):                1.326
Skew:                          -0.282   Prob(JB):                        0.515
Kurtosis:                       2.974   Cond. No.                         531.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
# Now we add some unrelated coefficients, that don't help at all.
# They do not add any value
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [7]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [8]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.974
Model:                            OLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                     276.9
Date:                Mon, 30 Sep 2024   Prob (F-statistic):           7.88e-64
Time:                        15:39:31   Log-Likelihood:                -369.84
No. Observations:                 100   AIC:                             765.7
Df Residuals:                      87   BIC:                             799.5
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -44.5443     11.268     -3.953      0.000     -66.941     -22.147
X1             1.0720      0.133      8.037      0.000       0.807       1.337
X2             1.5877      0.053     30.153      0.000       1.483       1.692
X3             1.1962      0.108     11.100      0.000       0.982       1.410
X4             0.7390      0.131      5.661      0.000       0.480       0.998
X5            -2.1287      0.059    -35.845      0.000      -2.247      -2.011
X6            -0.8597      0.103     -8.322      0.000      -1.065      -0.654
X7             0.0493      0.128      0.386      0.700      -0.205       0.303
X8            -0.0149      0.056     -0.266      0.791      -0.126       0.097
X9             0.0740      0.097      0.764      0.447      -0.119       0.267
X10            0.2075      0.126      1.645      0.104      -0.043       0.458
X11           -0.0780      0.055     -1.427      0.157      -0.187       0.031
X12            0.0754      0.094      0.804      0.424      -0.111       0.262
==============================================================================
Omnibus:                        1.517   Durbin-Watson:                   1.956
Prob(Omnibus):                  0.468   Jarque-Bera (JB):                1.533
Skew:                          -0.285   Prob(JB):                        0.465
Kurtosis:                       2.792   Cond. No.                     1.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.06125234,  1.5868322 ,  1.18630345,  0.72445014, -2.12556693,
       -0.85587641,  0.03428667, -0.01102057,  0.06742564,  0.19018219,
       -0.07330233,  0.06688027])

In [10]:
# Notice that as we increase alpha, the Lasso penalization will make the coefficients zero
# This makes it better for 
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 0.97664511,  1.57948388,  1.08410605,  0.59426333, -2.10780448,
       -0.81115857,  0.        , -0.        ,  0.00301632,  0.03566406,
       -0.02778975,  0.        ])

In [13]:
# New equation
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon + 2*x_7

In [14]:
# Use OLS model and calculate SSE, check significance
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)
X_ols['X7'] = pd.Series(x_7) # added

In [15]:
# Fit to model
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.973
Model:                            OLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                     478.3
Date:                Mon, 30 Sep 2024   Prob (F-statistic):           2.00e-69
Time:                        15:46:09   Log-Likelihood:                -372.59
No. Observations:                 100   AIC:                             761.2
Df Residuals:                      92   BIC:                             782.0
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -30.3390      8.134     -3.730      0.000     -46.494     -14.183
X1             1.0669      0.125      8.548      0.000       0.819       1.315
X2             1.5931      0.052     30.791      0.000       1.490       1.696
X3             1.1666      0.105     11.147      0.000       0.959       1.374
X4             0.7239      0.129      5.611      0.000       0.468       0.980
X5            -2.1504      0.057    -37.624      0.000      -2.264      -2.037
X6            -0.8783      0.099     -8.891      0.000      -1.075      -0.682
X7             2.0686      0.123     16.827      0.000       1.824       2.313
==============================================================================
Omnibus:                        1.411   Durbin-Watson:                   1.904
Prob(Omnibus):                  0.494   Jarque-Bera (JB):                1.310
Skew:                          -0.276   Prob(JB):                        0.519
Kurtosis:                       2.906   Cond. No.                         594.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
model_lasso = lm.Lasso(alpha=1).fit(X_ols,y)
model_lasso.coef_

array([ 0.        ,  1.05612586,  1.5914288 ,  1.15867217,  0.71093099,
       -2.14590378, -0.87150636,  2.05355854])

In [18]:
# Alpha for 1, 10, 20, 50, 100, 1000, etc.
alpha_list = [1,10,20,50,100,500,1000]

for item in alpha_list:
    print("f---------")
    print(f"Alpha of {item}:")
    model_lasso = lm.Lasso(alpha=item).fit(X_ols,y)
    print(model_lasso.coef_)

f---------
Alpha of 1:
[ 0.          1.05612586  1.5914288   1.15867217  0.71093099 -2.14590378
 -0.87150636  2.05355854]
f---------
Alpha of 10:
[ 0.          0.9588978   1.57608784  1.08717736  0.59403338 -2.10518452
 -0.80995587  1.9181755 ]
f---------
Alpha of 20:
[ 0.          0.85086644  1.55904226  1.00773876  0.4641473  -2.05994091
 -0.74156644  1.76774987]
f---------
Alpha of 50:
[ 0.          0.52677201  1.50790561  0.76942321  0.07448895 -1.92420998
 -0.53639811  1.31647293]
f---------
Alpha of 100:
[ 0.          0.          1.39846185  0.45149661  0.         -1.75950552
 -0.15902453  0.56462913]
f---------
Alpha of 500:
[ 0.          0.          0.56704019  0.          0.         -0.8248739
 -0.          0.        ]
f---------
Alpha of 1000:
[ 0.  0.  0.  0.  0. -0. -0.  0.]


# As Alpha inc

In [11]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.07051688,  1.58742523,  1.19515444,  0.73790802, -2.12806965,
       -0.85926129,  0.04898115, -0.0149311 ,  0.07440441,  0.20733892,
       -0.07786723,  0.07544804])

In [12]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.44715888,  1.33246696,  0.66898503,  0.26883977, -1.68596515,
       -0.5540377 , -0.05333385, -0.02864332,  0.1657037 ,  0.12561669,
       -0.00811941,  0.10601378])