In [1]:
# Import Statements
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [2]:
# Set up the variables
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [3]:
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon

In [4]:
# Use OLS model and calculate SSE, check significance
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [5]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.965
Model:                            OLS   Adj. R-squared:                  0.962
Method:                 Least Squares   F-statistic:                     423.2
Date:                Sat, 12 Oct 2024   Prob (F-statistic):           3.30e-65
Time:                        23:17:12   Log-Likelihood:                -382.18
No. Observations:                 100   AIC:                             778.4
Df Residuals:                      93   BIC:                             796.6
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -29.5498      7.940     -3.721      0.000     -45.318     -13.782
X1             1.3196      0.140      9.456      0.000       1.043       1.597
X2             1.6815      0.057     29.297      0.000       1.567       1.795
X3             1.0924      0.098     11.135      0.000       0.898       1.287
X4             0.7290      0.138      5.273      0.000       0.454       1.004
X5            -2.0578      0.057    -35.860      0.000      -2.172      -1.944
X6            -0.8698      0.095     -9.118      0.000      -1.059      -0.680
==============================================================================
Omnibus:                        0.366   Durbin-Watson:                   1.843
Prob(Omnibus):                  0.833   Jarque-Bera (JB):                0.534
Skew:                           0.065   Prob(JB):                        0.766
Kurtosis:                       2.667   Cond. No.                         485.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
# Now we add some unrelated coefficients, that don't help at all.
# They do not add any value
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [7]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [8]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.966
Model:                            OLS   Adj. R-squared:                  0.961
Method:                 Least Squares   F-statistic:                     204.7
Date:                Sat, 12 Oct 2024   Prob (F-statistic):           2.60e-58
Time:                        23:17:12   Log-Likelihood:                -380.56
No. Observations:                 100   AIC:                             787.1
Df Residuals:                      87   BIC:                             821.0
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -24.2110     12.251     -1.976      0.051     -48.561       0.139
X1             1.3364      0.145      9.247      0.000       1.049       1.624
X2             1.6923      0.059     28.595      0.000       1.575       1.810
X3             1.0939      0.103     10.623      0.000       0.889       1.299
X4             0.7444      0.146      5.099      0.000       0.454       1.035
X5            -2.0488      0.059    -34.591      0.000      -2.167      -1.931
X6            -0.8608      0.099     -8.695      0.000      -1.058      -0.664
X7            -0.1018      0.146     -0.698      0.487      -0.392       0.188
X8            -0.0368      0.056     -0.658      0.512      -0.148       0.074
X9            -0.0366      0.112     -0.326      0.745      -0.260       0.187
X10           -0.0033      0.154     -0.022      0.983      -0.309       0.302
X11            0.0696      0.058      1.190      0.237      -0.047       0.186
X12           -0.0437      0.104     -0.421      0.675      -0.250       0.162
==============================================================================
Omnibus:                        0.150   Durbin-Watson:                   1.880
Prob(Omnibus):                  0.928   Jarque-Bera (JB):                0.333
Skew:                          -0.003   Prob(JB):                        0.847
Kurtosis:                       2.717   Cond. No.                     1.03e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.03e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [9]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 1.32323662,  1.68876122,  1.08563884,  0.72610494, -2.04730237,
       -0.85404282, -0.08102755, -0.03445934, -0.02506399, -0.        ,
        0.06796072, -0.03337003])

In [10]:
# Notice that as we increase alpha, the Lasso penalization will make the coefficients zero
# This makes it better for 
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 1.21460384,  1.66191022,  1.01147397,  0.57023668, -2.02901135,
       -0.80701907, -0.        , -0.01980604, -0.        ,  0.        ,
        0.05016478, -0.        ])

In [11]:
# New equation
y=-30+1.3*x_1+1.6*x_2+1.1*x_3+0.7*x_4-2.1*x_5-0.9*x_6+epsilon + 2*x_7

In [12]:
# Use OLS model and calculate SSE, check significance
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)
X_ols['X7'] = pd.Series(x_7) # added

In [13]:
# Fit to model
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.969
Model:                            OLS   Adj. R-squared:                  0.967
Method:                 Least Squares   F-statistic:                     413.9
Date:                Sat, 12 Oct 2024   Prob (F-statistic):           1.26e-66
Time:                        23:17:13   Log-Likelihood:                -381.69
No. Observations:                 100   AIC:                             779.4
Df Residuals:                      92   BIC:                             800.2
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -27.0979      8.353     -3.244      0.002     -43.687     -10.508
X1             1.3186      0.140      9.444      0.000       1.041       1.596
X2             1.6886      0.058     29.160      0.000       1.574       1.804
X3             1.1031      0.099     11.165      0.000       0.907       1.299
X4             0.7542      0.141      5.355      0.000       0.475       1.034
X5            -2.0586      0.057    -35.851      0.000      -2.173      -1.945
X6            -0.8708      0.095     -9.123      0.000      -1.060      -0.681
X7             1.8670      0.140     13.344      0.000       1.589       2.145
==============================================================================
Omnibus:                        0.481   Durbin-Watson:                   1.865
Prob(Omnibus):                  0.786   Jarque-Bera (JB):                0.634
Skew:                           0.091   Prob(JB):                        0.728
Kurtosis:                       2.655   Cond. No.                         542.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
model_lasso = lm.Lasso(alpha=1).fit(X_ols,y)
model_lasso.coef_

array([ 0.        ,  1.30726234,  1.6867141 ,  1.09580611,  0.7402515 ,
       -2.05624806, -0.86576403,  1.85702104])

In [15]:
# Alpha for 1, 10, 20, 50, 100, 1000, etc.
alpha_list = [1,10,20,50,100,500,1000]

for item in alpha_list:
    print("f---------")
    print(f"Alpha of {item}:")
    model_lasso = lm.Lasso(alpha=item).fit(X_ols,y)
    print(model_lasso.coef_)

f---------
Alpha of 1:
[ 0.          1.30726234  1.6867141   1.09580611  0.7402515  -2.05624806
 -0.86576403  1.85702104]
f---------
Alpha of 10:
[ 0.          1.20513738  1.6700745   1.02964312  0.61441474 -2.03535214
 -0.82014507  1.76716933]
f---------
Alpha of 20:
[ 0.          1.09166521  1.65158606  0.95612867  0.47459612 -2.01213445
 -0.76945734  1.6673341 ]
f---------
Alpha of 50:
[ 0.          0.75124869  1.59612074  0.73558535  0.05514024 -1.94248137
 -0.61739416  1.36782839]
f---------
Alpha of 100:
[ 0.          0.18661871  1.51815225  0.46996519  0.         -1.8354227
 -0.30949949  0.74806444]
f---------
Alpha of 500:
[ 0.          0.          0.53516567  0.          0.         -0.81458524
 -0.          0.        ]
f---------
Alpha of 1000:
[ 0.  0.  0.  0.  0. -0. -0.  0.]


# As Alpha inc

In [16]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 1.33478106,  1.69198898,  1.09333506,  0.74351704, -2.04838466,
       -0.86041399,  1.89571362, -0.0368488 , -0.03673396, -0.00367903,
        0.06938648, -0.0437014 ])

In [17]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.66549075,  1.39200006,  0.68528664,  0.32404186, -1.65218761,
       -0.54926813,  0.86434835, -0.06700612, -0.04830878, -0.06998525,
       -0.01289578, -0.05593639])